### PR TITLE
Fixes #26 - [Feature Request] Support of phasing out third-party cookies

### LINKED ISSUE #26: [Feature Request] Support of phasing out third-party cookies
Hi
Google plans soon to activate phasing out third-party cookies
See Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

Doc about phasing out third-party cookies: https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

This feature request requires the possibility to add "Partitioned" to the cookie like Secure.

### PR DESCRIPTION
**Pull request by sbordet**
Added support for cookie attributes: Domain, Path, Max-Age, Partitioned.

### CODE REVIEW

**Comment by sbordet** [comment]
@nicob-29  @sblecon this PR implements support for the `Partitioned` attribute.
Can you try it out and verify that it works for you?

**Comment by nicob-29** [comment]
@sbordet 
Yep, I'll do that tomorrow !

**Comment by nicob-29** [comment]
Hi @sbordet 
I updated our application with your PR
image
Seem good but I need to perform some other tests. 
I'll provide you on Monday final confirmation.

**Comment by nicob-29** [comment]
It is OK for me.
I test with **jsfiddle** and iframe to embed my application

**Pull request merged**
